# Generated by Django 3.2.7 on 2022-01-17 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('memory', models.IntegerField()),
                ('vendor', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Interfaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('FastEthernet', 'FastEthernet'), ('GigabitEthernet', 'GigabitEthernet')], max_length=20)),
                ('slot', models.IntegerField(choices=[(0, 'Slot 0'), (1, 'Slot 1')], default=0)),
                ('port', models.IntegerField(choices=[(0, 'Port 0'), (1, 'Port 1'), (2, 'Port 2'), (3, 'Port 3')], default=0)),
                ('ip4_address', models.CharField(default=None, max_length=16, null=True)),
                ('status', models.CharField(choices=[('u', 'Up'), ('d', 'Down')], max_length=4)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.devices')),
            ],
        ),
    ]
