# Generated by Django 3.2.7 on 2022-07-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tokens',
            name='unique token',
        ),
        migrations.AddConstraint(
            model_name='tokens',
            constraint=models.UniqueConstraint(fields=('token', 'name'), name='unique token'),
        ),
    ]
