# Generated by Django 3.2.7 on 2022-01-19 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WebApp', '0002_auto_20220117_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('memory', models.IntegerField()),
                ('vendor', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Interfaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('slot', models.IntegerField()),
                ('port', models.IntegerField()),
                ('ip4_address', models.CharField(default=None, max_length=16, null=True)),
                ('status', models.CharField(max_length=4)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.devices')),
            ],
        ),
    ]
