# Generated by Django 3.2.7 on 2022-01-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_devices_interfaces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interfaces',
            name='device',
        ),
        migrations.DeleteModel(
            name='Devices',
        ),
        migrations.DeleteModel(
            name='Interfaces',
        ),
    ]
