# Generated by Django 3.2.7 on 2022-01-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_auto_20220119_1759'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='interfaces',
            constraint=models.UniqueConstraint(fields=('device', 'type', 'slot', 'port'), name='unique slot-port'),
        ),
    ]
