# Generated by Django 3.2.7 on 2022-03-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0009_alter_usuarios_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaces',
            name='type',
            field=models.CharField(choices=[('Fast', 'FastEthernet'), ('Giga', 'GigabitEthernet')], default='Fast', max_length=20),
        ),
    ]
