# Generated by Django 3.2.7 on 2022-03-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0010_alter_interfaces_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usuarios',
            constraint=models.UniqueConstraint(fields=('usuario',), name='unique user'),
        ),
    ]
